sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: '12'
install: echo "install happens when run setup"
script:
  - yarn setup
  - yarn global add codecov
after_script: codecov
branches:
  only: master
